### ISSUE TITLE
Problems with Keymapping (ISO layout and Ajazz AK33)

### ISSUE THREAD

**Issue by keinLeerzeichen** [dokutan/rgb_keyboard#1]
I noticed that, whenever i try to remap a key the keymap ends up remapping my whole keyboard (spacebar becomes "m" and so on). I am using a an ISO 60% GMMK, so im thinking the ISO layout might be the problem.

**Comment by dokutan** [comment]
I have added a new branch iso-keymapping that should hopefully address that issue. It would be great if you could test it and reply back with the results. If it fully works (remapping of the Int_Key (<,>,|, etc.) and profiles) i will merge the changes to master.

**Comment by keinLeerzeichen** [comment]
Hi, sadly, the problem persists (unless downloading the new branch and using the same commands was wrong^^). The whole keymap is still shifted, tell me if i can help you with testing in any way.
Edit: Additional info:
I am using a german ISO layout so i have ö,ä,ü as seperate keys for example

**Comment by dokutan** [comment]
Dumb question, did you run make clean befor make upgrade? Also try running the new binary directly from where it was compiled, maybe you were still somehow using the old version.

What i did: I used the ISO version of the official software, and captured the usb communication, this was different from the ANSI version, but it still worked on the ANSI keyboard. Also when remapping the Int_Key it showed up correctly in the official software, even though the key doesn't eyxist on my keyboard.

If you want to help out: You could set up the official software in a Windows VM (QEMU or VirtualBox) with usb passthrough and capture the usb communication with wireshark. Feel free to ask if you need any help, i will add some information about the protocol to the doc directory in master, so look there and in the sourcecode for information. Some links for getting started:
[https://blog.davehylands.com/capturing-usb-serial-using-wireshark/](https://blog.davehylands.com/capturing-usb-serial-using-wireshark/)
[https://wiki.wireshark.org/CaptureSetup/USB](https://wiki.wireshark.org/CaptureSetup/USB)

**Comment by keinLeerzeichen** [comment]
Since im very new to git and linux in general i actually removed the whole rgb_keyboard folder and cloned the new one using (im using ubuntu) : git clone -b ISO-keymap ttps://github.com/dokutan/rgb_keyboard.
So i think i should have had to use the correct version.
I have a Windows desktop could i do the wireshark thing from that instead of using a VM?

**Comment by dokutan** [comment]
I don't know if wireshark is able to do usb sniffing on windows, from a quick search online it appears to be the case, [maybe this helps](https://geekthis.net/post/usb-sniffing-and-programming/), unfortunately that is something i can't really say anything about, because i don't have a windows pc to try it out.
The git command you provided, does not work, the branch name is wrong and the h from https is missing, i am assuming you didn't make these mistakes when cloning. Just in case the working version is:
``
 git clone https://github.com/dokutan/rgb_keyboard -b iso-keymapping
``
To check wether the version is correct, look inside the include/ directory, only in the iso-keymapping branch a file named data_keymap exists.

**Comment by keinLeerzeichen** [comment]
Ok i did clone correctly. I'll look into the Wireshark stuff and do that if I understand it otherwise you'll hear from me again.

**Comment by dokutan** [comment]
That's good to hear, if you have any remaining questions, particularly to what you are looking for in wireshark, feel free to ask.

**Comment by keinLeerzeichen** [comment]
I set up a VM using qemu and KVM now because i have found a guide that explains that in extreme detail. But now i have trouble bridging my network connection to my VM.

**Comment by dokutan** [comment]
The QEMU wiki should help, look in the Guest Hints section: [https://wiki.qemu.org/Documentation/Networking](https://wiki.qemu.org/Documentation/Networking).
If everything fails but you are able to install windows (maybe 7) without a network connection, you can downlaod the installer for the keyboard software on linux and transfer it to the VM via an .iso, or by mounting the VM disk image with guestmount.
Edit: working on one of my VMs ,remove the (,hostfwd=tcp::5555-:5900,restrict=y): 
``
-device e1000,netdev=net0 -netdev user,id=net0,hostfwd=tcp::5555-:5900,restrict=y
``

**Comment by keinLeerzeichen** [comment]
My Win10 in VM now has an internet connection 👍. And i now have wireshark running on my Windows VM with USBPcap. I am not completely sure what data you need exactly, so could you maybe give an example of how it would look like? thanks

**Comment by dokutan** [comment]
Im sorry, i guess caused a slight misunderstanding, the purpose of the VM is that you are able to run wireshark on the linux host, which is much easier.
Have you got the usb passthrough of the keyboard working?
If yes, try loading the usbmon kernel module and capturing some usb communication between the keyboard and rhe VM, (look at the wireshark display filter, so you don't see the communication to other devices).
As soon as i am back home i will add some captured data as an example to the doc directory in the master branch.

**Comment by dokutan** [comment]
I have added a generic description of the capture process and a screenshot to doc/README.md in master. In this particular case when applying a keymapping, there will be more than one data packet, i encountered 8 or 11 (in addition, start and end), in your case the number might be different.
What you need to capture is the data for the default keymapping. You can export the data by selecting all interesting packets and the choosing File>Export Packet Dissections>As "C" Arrays and choosing selected packets only.

**Comment by dokutan** [comment]
I'm closing this issue as it seems to be inactive and partially resolved.

I confirmed that keymapping works on an Tecware Phantom TKL ISO keyboard, so the problem seems to be limited to the 60% GMMK and Ajazz AK33. Furthermore this issue is noted in the README and when remapping the keys a warning is shown and the user gets asked for confirmation.

If someone has a keyboard that is affected by this problem and is interested in providing the captured data, please open a new issue specific to to that keyboard.
