### ISSUE TITLE
Redragon K512 Support

### ISSUE THREAD

**Issue by Raddagast** [dokutan/rgb_keyboard#18]
Hi I was wondering if it'll be possible to add support for the Redragon Shiva K512. Upon running rgb_keyboard --list-keys arg it outputs Could not detect keyboard, check hardware and permissions.
This is what I get from lsusb
Bus 003 Device 002: ID 0c45:672e Microdia USB DEVICE
Please let me know if any more info is required

**Comment by dokutan** [comment]
I have added the product id in 838ca76d552a0caa30bf52bc3aca02b8aee64380 and 58d221c77a8e1cc4f38a84e3632dfaac1e546a8b. You should now be able to try out this software.

>  Please let me know if any more info is required

You might need to use the ``-C false`` argument, please tell me if that is the case or you encounter any problems.
