### ISSUE TITLE
Custom Pattern Documentation

### ISSUE THREAD

**Issue by sylv256** [dokutan/rgb_keyboard#20]
It'd be very helpful to know how to create custom patterns, especially ones like pulse and reactive patterns.

**Comment by dokutan** [comment]
Unfortunately it is not possible to create custom animations on these keyboards, the custom patterns allow statically and individually setting the color of the keys. The pattern [example](https://github.com/dokutan/rgb_keyboard/blob/master/examples/example.conf) should be self-explanatory.

A possible workaroud is write a script to constantly update the key colors as described [here](https://github.com/dokutan/rgb_keyboard#change-custom-key-colors-from-the-commandline). However this is far from ideal as it would wear out the flash memory on the keyboard and requires a constantly running program. Therefore i do not recommend or support this method.
