### ISSUE TITLE
Redragon k585 color support for multiple profiles 

### ISSUE THREAD

**Issue by SenorSmartyPants** [dokutan/rgb_keyboard#28]
Does this support the k585, specifically setting individual key colors on profiles m2-m4?

I've been using openrgb but can only do m1 profile.

**Comment by dokutan** [comment]
I can't give you an answer to that question as i don't have a K585 to test with, i don't even know if the K585 is compatible at all, as nobody tested it and reported the results.

I suggest that you simply try it out. If you report your results and the output of `lsusb` i can update the README.
